2025-02-15 17:56:24.282681: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-15 17:56:24.347831: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1739660184.366140  626814 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739660184.372003  626814 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-15 17:56:24.393048: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0215 17:57:17.142915 22719756182528 main.py:395] Seed: 0
I0215 17:57:17.167862 22719756182528 utils.py:24] Experiment directory: /tmp/experiments/unnamed
I0215 17:57:17.174900 22719756182528 main.py:428] Model config: {
    "address_embedder": {
        "embed_dim": 64,
        "max_vocab_size": 10000,
        "type": "dynamic-vocab"
    },
    "cache_line_embedder": "address_embedder",
    "cache_pc_embedder": "none",
    "loss": [
        "log_likelihood"
    ],
    "lr": 0.001,
    "lstm_hidden_size": 128,
    "max_attention_history": 30,
    "pc_embedder": {
        "embed_dim": 64,
        "max_vocab_size": 5000,
        "type": "dynamic-vocab"
    },
    "positional_embedder": {
        "embed_dim": 128,
        "type": "positional"
    },
    "sequence_length": 80
}
I0215 17:57:17.180982 22719756182528 main.py:434] Cache config: {
    "associativity": 16,
    "cache_line_size": 64,
    "capacity": 2097152
}
I0215 17:57:17.186311 22719756182528 main.py:440] DAgger config: {
    "final": 1.0,
    "initial": 0.0,
    "num_steps": 200000,
    "type": "linear",
    "update_freq": 10000
}
/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/torch/__init__.py:1144: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)
I0215 17:57:17.190227 22719756182528 main.py:450] Device: cuda:0
Traceback (most recent call last):
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs_common/share01/csc591s25/adhage/GenAI-for-Systems-Gym/homework-1/models/MLP/cache_replacement/policy_learning/cache_model/main.py", line 569, in <module>
    app.run(main)
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/gpfs_common/share01/csc591s25/adhage/GenAI-for-Systems-Gym/homework-1/models/MLP/cache_replacement/policy_learning/cache_model/main.py", line 457, in main
    oracle_valid_data, hit_rates = next(measure_cache_hit_rate(
  File "/gpfs_common/share01/csc591s25/adhage/GenAI-for-Systems-Gym/homework-1/models/MLP/cache_replacement/policy_learning/cache_model/main.py", line 302, in measure_cache_hit_rate
    with memtrace.MemoryTrace(memtrace_path, cache_line_size=line_size) as trace:
  File "/gpfs_common/share01/csc591s25/adhage/GenAI-for-Systems-Gym/homework-1/models/MLP/cache_replacement/policy_learning/cache/memtrace.py", line 118, in __enter__
    self._file = open(self._filename, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'cache_replacement/policy_learning/cache/traces/omnetpp_valid.csv'
/home/adhage/.lsbatch/1739659940.893898.shell: line 32: --experiment_base_dir=/share/csc591s25/adhage/GenAI-for-Systems-Gym/homework-1/models/MLP/experiments: No such file or directory
/home/adhage/.lsbatch/1739659940.893898.shell: line 34: --experiment_name=train_mlp_neuron32: command not found
/home/adhage/.lsbatch/1739659940.893898.shell: line 36: --cache_configs=cache_replacement/policy_learning/cache/configs/default.json: No such file or directory
/home/adhage/.lsbatch/1739659940.893898.shell: line 38: --model_bindings=address_embedder.max_vocab_size=5000: command not found
/home/adhage/.lsbatch/1739659940.893898.shell: line 40: --model_bindings=lstm_hidden_size=32: command not found
/home/adhage/.lsbatch/1739659940.893898.shell: line 42: --train_memtrace=/share/csc591s25/traces/astar_313B_train.csv: No such file or directory
/home/adhage/.lsbatch/1739659940.893898.shell: line 43: --valid_memtrace=/share/csc591s25/traces/astar_313B_valid.csv: No such file or directory
